server:
  port: 8001

spring:
  application:
    name: matching-service
    activate:
      on-profile: prd
  config:
    import: optional:configserver:http://config-service:8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    defaultZone: http://discovery-service:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, refresh, metrics